from .IAconfig import IMAGE_IA_GEN_BODY_BASE,IMAGE_IA_GEN_ENDPOINT_GEN, IMAGE_IA_GEN_ENDPOINT_METHOD, IMAGE_IA_GEN_REST_URL
#from .cardImageConfig import saveOutputCardSize
from .MysqlConfig import SCHEMA_NAME, DB_HOST, DB_PORT, DB_PASSWORD, DB_USER
__all__=[
    #"saveOutputCardSize",
    "SCHEMA_NAME","DB_PORT","DB_HOST", "DB_PASSWORD", "DB_USER,"
    "IMAGE_IA_GEN_BODY_BASE", "IMAGE_IA_GEN_ENDPOINT_GEN","IMAGE_IA_GEN_ENDPOINT_METHOD","IMAGE_IA_GEN_REST_URL"]